### ISSUE TITLE
Can't install matlib package

### ISSUE THREAD

**Issue by ghost** [friendly/matlib#35]
Hello, 
When although I can install the package, when loading it using library function, I get the following error: 
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rgl/libs/rgl.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rgl/libs/rgl.so, 6): Library not loaded: /opt/X11/lib/libGLU.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rgl/libs/rgl.so
  Reason: image not found
Error: package or namespace load failed for ‘matlib’:
 .onLoad failed in loadNamespace() for 'rgl', details:
  call: NULL
  error: 	Loading rgl's DLL failed. 
	On MacOS, rgl depends on XQuartz, which you can download from xquartz.org.

**Comment by friendly** [comment]
This indicates a problem with rgl on your system.  Try reinstalling it in a fresh session

install.packages("rgl")

is how you install a package. Not `library(rgl)`

**Comment by john-d-fox** [comment]
Actually, matlib "imports" from rgl and so when the matlib package is loaded so is the namespace of rgl, which is what failed here. The original poster is correct that XQuartz is required by rgl on macOS. What I don't get is why that's a problem, since the original poster knows what the solution is.
