### ISSUE TITLE
conflicts in `latexMatrixOperations.R`

### ISSUE THREAD

**Issue by john-d-fox** [friendly/matlib#60]
I'm afraid that Michael and I were editing `latexMatrixOperations.R` at the same time. I made changes to the Roxygen .Rd markup, to the examples, and to the code in the file. (I also made similar changes to `latexMatrix.R` but Michael didn't edit that file.)

After trying to resolve the conflicts in the two versions of `latexMatrixOperations.R`, I decided that the differences were too profound, and I just ended up substituting my version of the file (now on GitHub) for Michael's edited version. I did this because my fixes to the code, edits to the .Rd documentation, and new examples represented several hours of work.

I'll leave `latexMatrixOperations.R`and `latexMatrix.R` alone now, so feel free to edit them.

I didn't touch the vignettes, which probably should also be updated. I'll also leave those alone.

**Comment by philchalmers** [comment]
Hi John,

If it's not too late, Michael can make a different branch from his local version, push that to Github, and the rest can be cherry-picked of manually inspected as to whether any code/idea merges are worthwhile (@friendly you'll want to `hard --reset` your main branch after so that you can merge John's version without breaking your git history). Moving forward if there are chances that we're working on the same files, and the changes are larger, then temporary branches should be constructed until they are ready to merge into the `master` branch.

**Comment by john-d-fox** [comment]
Using branches for substantial changes is a good idea, but I still think that it's a bad idea for two or more of us to work on the same file simultaneously, even in separate branches. If we do, and make incompatible changes, then they will eventually have to be reconciled manually. Maybe this reflects my naive understanding of Git (though I have used branches in this way before).
